<?php

use Illuminate\Database\Seeder;
use App\Models\Management\Ambiente;

class AmbienteSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
    	$created_at = Carbon\Carbon::now();

    	$ambientes[] = ['codigo' => '000.18.01', 'name' => 'AEROPORTO'];
    	$ambientes[] = ['codigo' => '000.03.01', 'name' => 'AGENCIA BANCARIA'];
    	$ambientes[] = ['codigo' => '000.08.01', 'name' => 'ALOJAMENTO COLETIVO'];
    	$ambientes[] = ['codigo' => '000.12.06', 'name' => 'AREA DE PRESERVACAO PERMANENTE (APP)'];
    	$ambientes[] = ['codigo' => '000.23.07', 'name' => 'AREA DE PROTECAO AMBIENTAL (APA)'];
    	$ambientes[] = ['codigo' => '000.23.09', 'name' => 'AREA DE RELEVANTE INTERESSE ECOLOGICO'];
    	$ambientes[] = ['codigo' => '000.02.10', 'name' => 'ASSOCIACAO EDUCACIONAL'];
    	$ambientes[] = ['codigo' => '000.02.09', 'name' => 'ASSOCIACAO FILANTROPICA'];
    	$ambientes[] = ['codigo' => '000.02.05', 'name' => 'ASSOCIACAO POLITICA'];
    	$ambientes[] = ['codigo' => '000.02.06', 'name' => 'ASSOCIACAO RELIGIOSA'];
    	$ambientes[] = ['codigo' => '000.12.04', 'name' => 'BAIA'];
    	$ambientes[] = ['codigo' => '000.04.04', 'name' => 'BANCA DE REVISTAS'];
    	$ambientes[] = ['codigo' => '000.01.01', 'name' => 'BAR'];
    	$ambientes[] = ['codigo' => '000.12.10', 'name' => 'BARRACAO'];
    	$ambientes[] = ['codigo' => '000.01.02', 'name' => 'BINGO'];
    	$ambientes[] = ['codigo' => '000.01.03', 'name' => 'BOATE'];
    	$ambientes[] = ['codigo' => '000.01.04', 'name' => 'BOLICHE'];
    	$ambientes[] = ['codigo' => '000.14.01', 'name' => 'BOSQUE'];
    	$ambientes[] = ['codigo' => '000.18.15', 'name' => 'CABIFY'];
    	$ambientes[] = ['codigo' => '000.03.02', 'name' => 'CAIXA ELETRONICO'];
    	$ambientes[] = ['codigo' => '000.03.03', 'name' => 'CASA DE CAMBIO'];
    	$ambientes[] = ['codigo' => '000.12.08', 'name' => 'CASA DE MASSAGENS'];
    	$ambientes[] = ['codigo' => '000.01.05', 'name' => 'CASA DE SHOW'];
    	$ambientes[] = ['codigo' => '000.12.09', 'name' => 'CEMITERIO'];
    	$ambientes[] = ['codigo' => '000.01.15', 'name' => 'CERAMICA'];
    	$ambientes[] = ['codigo' => '000.20.02', 'name' => 'CHACARA'];
    	$ambientes[] = ['codigo' => '000.01.06', 'name' => 'CIRCO'];
    	$ambientes[] = ['codigo' => '000.17.01', 'name' => 'CLINICAS'];
    	$ambientes[] = ['codigo' => '000.02.01', 'name' => 'CLUBE CULTURAL'];
    	$ambientes[] = ['codigo' => '000.02.02', 'name' => 'CLUBE DESPORTIVO'];
    	$ambientes[] = ['codigo' => '000.02.03', 'name' => 'CLUBE SOCIAL'];
    	$ambientes[] = ['codigo' => '000.04.02', 'name' => 'COMERCIO ATACADISTA'];
    	$ambientes[] = ['codigo' => '000.04.03', 'name' => 'COMERCIO DE AUTO PECAS'];
    	$ambientes[] = ['codigo' => '000.04.05', 'name' => 'COMERCIO DE BEBIDAS'];
    	$ambientes[] = ['codigo' => '000.04.06', 'name' => 'COMERCIO DE CALCADOS'];
    	$ambientes[] = ['codigo' => '000.04.07', 'name' => 'COMERCIO DEDERIVADOS ARMAS E MUNICOES'];
    	$ambientes[] = ['codigo' => '000.04.08', 'name' => 'COMERCIO DE ELETROELETRONICO'];
    	$ambientes[] = ['codigo' => '000.04.11', 'name' => 'COMERCIO DE INFORMATICA'];
    	$ambientes[] = ['codigo' => '000.04.09', 'name' => 'COMERCIO DE JOIAS / RELOGIOS'];
    	$ambientes[] = ['codigo' => '000.04.13', 'name' => 'COMERCIO DE MATERIAL ESPORTIVO'];
    	$ambientes[] = ['codigo' => '000.04.19', 'name' => 'COMERCIO DE TINTAS'];
    	$ambientes[] = ['codigo' => '000.04.20', 'name' => 'COMERCIO DE VEICULOS'];
    	$ambientes[] = ['codigo' => '000.04.21', 'name' => 'COMERCIO DE VESTUARIO'];
    	$ambientes[] = ['codigo' => '000.04.12', 'name' => 'COMERCIO MATERIAL DE CONSTRUCAO'];
    	$ambientes[] = ['codigo' => '000.04.01', 'name' => 'COMERCIO VAREJISTA'];
    	$ambientes[] = ['codigo' => '000.07.01', 'name' => 'COMICIO'];
    	$ambientes[] = ['codigo' => '000.07.02', 'name' => 'COMPETICOES DESPORTIVAS'];
    	$ambientes[] = ['codigo' => '000.07.03', 'name' => 'COMPETICOES MOTORIZADAS'];
    	$ambientes[] = ['codigo' => '000.02.04', 'name' => 'CONDOMINIO'];
    	$ambientes[] = ['codigo' => '000.04.15', 'name' => 'CONFEITARIA'];
    	$ambientes[] = ['codigo' => '000.02.07', 'name' => 'CONSELHO DE BAIRRO'];
    	$ambientes[] = ['codigo' => '000.17.02', 'name' => 'CONSULTORIO MEDICO'];
    	$ambientes[] = ['codigo' => '000.17.03', 'name' => 'CONSULTORIO ODONTOLOGICO'];
    	$ambientes[] = ['codigo' => '000.15.01', 'name' => 'CONVENTO'];
    	$ambientes[] = ['codigo' => '000.02.08', 'name' => 'COOPERATIVA'];
    	$ambientes[] = ['codigo' => '000.07.04', 'name' => 'CULTO RELIGIOSO'];
    	$ambientes[] = ['codigo' => '000.01.07', 'name' => 'DANCETERIA'];
    	$ambientes[] = ['codigo' => '000.18.10', 'name' => 'DE CARGA'];
    	$ambientes[] = ['codigo' => '000.11.08', 'name' => 'DELEGACIA DE POLICIA'];
    	$ambientes[] = ['codigo' => '000.12.01', 'name' => 'DESCONHECIDO'];
    	$ambientes[] = ['codigo' => '000.05.01', 'name' => 'DISTRIBUIDOR DE GAS'];
    	$ambientes[] = ['codigo' => '000.16.04', 'name' => 'EM CONSTRUCAO'];
    	$ambientes[] = ['codigo' => '000.04.24', 'name' => 'EMPRESA'];
    	$ambientes[] = ['codigo' => '000.13.02', 'name' => 'ESCRITORIO'];
    	$ambientes[] = ['codigo' => '000.06.01', 'name' => 'ESTABELECIMENTO DE ENSINO ESTADUAL'];
    	$ambientes[] = ['codigo' => '000.06.02', 'name' => 'ESTABELECIMENTO DE ENSINO FEDERAL'];
    	$ambientes[] = ['codigo' => '000.06.03', 'name' => 'ESTABELECIMENTO DE ENSINO MUNICIPAL'];
    	$ambientes[] = ['codigo' => '000.06.04', 'name' => 'ESTABELECIMENTO DE ENSINO PARTICULAR'];
    	$ambientes[] = ['codigo' => '000.06.05', 'name' => 'ESTABELECIMENTO DE ENSINO RELIGIOSO'];
    	$ambientes[] = ['codigo' => '000.23.02', 'name' => 'ESTACAO ECOLOGICA'];
    	$ambientes[] = ['codigo' => '000.13.03', 'name' => 'ESTACIONAMENTO'];
    	$ambientes[] = ['codigo' => '000.07.10', 'name' => 'EVENTO BENEFICENTE'];
    	$ambientes[] = ['codigo' => '000.07.11', 'name' => 'EVENTO RELIGIOSO'];
    	$ambientes[] = ['codigo' => '000.07.05', 'name' => 'EXPOSICAO / FEIRA'];
    	$ambientes[] = ['codigo' => '000.17.04', 'name' => 'FARMACIA'];
    	$ambientes[] = ['codigo' => '000.17.07', 'name' => 'FARMACIA 24H'];
    	$ambientes[] = ['codigo' => '000.20.01', 'name' => 'FAZENDA'];
    	$ambientes[] = ['codigo' => '000.10.02', 'name' => 'FEIRA'];
    	$ambientes[] = ['codigo' => '000.18.02', 'name' => 'FERROVIARIO'];
    	$ambientes[] = ['codigo' => '000.20.06', 'name' => 'FLORESTA'];
    	$ambientes[] = ['codigo' => '000.23.06', 'name' => 'FLORESTA NACIONAL'];
    	$ambientes[] = ['codigo' => '000.21.01', 'name' => 'FRONTEIRA ESTADUAL'];
    	$ambientes[] = ['codigo' => '000.21.02', 'name' => 'FRONTEIRA INTERNACIONAL'];
    	$ambientes[] = ['codigo' => '000.07.06', 'name' => 'FUTEBOL ESTADIO'];
    	$ambientes[] = ['codigo' => '000.07.07', 'name' => 'GREVES'];
    	$ambientes[] = ['codigo' => '000.10.03', 'name' => 'HIPERMERCADO'];
    	$ambientes[] = ['codigo' => '000.08.02', 'name' => 'HOSPEDARIA'];
    	$ambientes[] = ['codigo' => '000.17.05', 'name' => 'HOSPITAL'];
    	$ambientes[] = ['codigo' => '000.08.03', 'name' => 'HOTEL'];
    	$ambientes[] = ['codigo' => '000.15.03', 'name' => 'IGREJA / TEMPLO'];
    	$ambientes[] = ['codigo' => '000.18.16', 'name' => 'INDRIVER'];
    	$ambientes[] = ['codigo' => '000.09.01', 'name' => 'INDUSTRIA ALIMENTICIA'];
    	$ambientes[] = ['codigo' => '000.09.02', 'name' => 'INDUSTRIA AUTOMOBILISTICA'];
    	$ambientes[] = ['codigo' => '000.09.03', 'name' => 'INDUSTRIA CERAMICA'];
    	$ambientes[] = ['codigo' => '000.09.04', 'name' => 'INDUSTRIA MADEIREIRA'];
    	$ambientes[] = ['codigo' => '000.09.05', 'name' => 'INDUSTRIA MOVELEIRA'];
    	$ambientes[] = ['codigo' => '000.09.06', 'name' => 'INDUSTRIA PAPEL / CELULOSE'];
    	$ambientes[] = ['codigo' => '000.09.07', 'name' => 'INDUSTRIA PETROQUIMICA/QUIMICA'];
    	$ambientes[] = ['codigo' => '000.09.08', 'name' => 'INDUSTRIA SIDERURGICA/MEALURGICA'];
    	$ambientes[] = ['codigo' => '000.03.06', 'name' => 'INSTITUICAO FINANCEIRA'];
    	$ambientes[] = ['codigo' => '000.07.08', 'name' => 'INVASOES'];
    	$ambientes[] = ['codigo' => '000.01.08', 'name' => 'JOGOS ELETRONICOS'];
    	$ambientes[] = ['codigo' => '000.20.08', 'name' => 'LAGOA'];
    	$ambientes[] = ['codigo' => '000.01.09', 'name' => 'LANCHONETE'];
    	$ambientes[] = ['codigo' => '000.07.09', 'name' => 'LEILOES'];
    	$ambientes[] = ['codigo' => '000.04.14', 'name' => 'LIVRARIA'];
    	$ambientes[] = ['codigo' => '000.04.10', 'name' => 'LOTERICAS'];
    	$ambientes[] = ['codigo' => '000.12.03', 'name' => 'MAR'];
    	$ambientes[] = ['codigo' => '000.20.05', 'name' => 'MATA'];
    	$ambientes[] = ['codigo' => '000.10.01', 'name' => 'MERCADO AMBULANTE'];
    	$ambientes[] = ['codigo' => '000.10.04', 'name' => 'MERCEARIA'];
    	$ambientes[] = ['codigo' => '000.14.13', 'name' => 'MONTANHA'];
    	$ambientes[] = ['codigo' => '000.23.13', 'name' => 'MONUMENTO NATURAL'];
    	$ambientes[] = ['codigo' => '000.16.02', 'name' => 'MORADOR AUSENTE'];
    	$ambientes[] = ['codigo' => '000.08.04', 'name' => 'MOTEL'];
    	$ambientes[] = ['codigo' => '000.12.11', 'name' => 'NÃO INFORMADO'];
    	$ambientes[] = ['codigo' => '000.18.03', 'name' => 'ONIBUS'];
    	$ambientes[] = ['codigo' => '000.11.05', 'name' => 'ORGAO PUBLICO ESTADUAL'];
    	$ambientes[] = ['codigo' => '000.11.02', 'name' => 'ORGAO PUBLICO FEDERAL'];
    	$ambientes[] = ['codigo' => '000.11.03', 'name' => 'ORGAO PUBLICO INTERNACIONAL'];
    	$ambientes[] = ['codigo' => '000.11.04', 'name' => 'ORGAO PUBLICO MUNICIPAL'];
    	$ambientes[] = ['codigo' => '000.12.02', 'name' => 'OUTROS'];
    	$ambientes[] = ['codigo' => '000.03.05', 'name' => 'PAB'];
    	$ambientes[] = ['codigo' => '000.04.16', 'name' => 'PANIFICADORA'];
    	$ambientes[] = ['codigo' => '000.04.23', 'name' => 'PANIFICADORA 24 HORAS'];
    	$ambientes[] = ['codigo' => '000.04.17', 'name' => 'PAPELARIA'];
    	$ambientes[] = ['codigo' => '000.01.10', 'name' => 'PARQUE DE DIVERSAO'];
    	$ambientes[] = ['codigo' => '000.23.04', 'name' => 'PARQUE ESTADUAL'];
    	$ambientes[] = ['codigo' => '000.23.05', 'name' => 'PARQUE MUNICIPAL'];
    	$ambientes[] = ['codigo' => '000.23.03', 'name' => 'PARQUE NACIONAL'];
    	$ambientes[] = ['codigo' => '000.14.02', 'name' => 'PARQUES'];
    	$ambientes[] = ['codigo' => '000.07.12', 'name' => 'PASSEATA'];
    	$ambientes[] = ['codigo' => '000.08.05', 'name' => 'PENSAO'];
    	$ambientes[] = ['codigo' => '000.01.11', 'name' => 'PIZZARIA'];
    	$ambientes[] = ['codigo' => '000.18.04', 'name' => 'PONTO'];
    	$ambientes[] = ['codigo' => '000.18.05', 'name' => 'PORTO'];
    	$ambientes[] = ['codigo' => '000.05.02', 'name' => 'POSTO DE COMBUSTIVEL'];
    	$ambientes[] = ['codigo' => '000.17.06', 'name' => 'POSTO SAUDE'];
    	$ambientes[] = ['codigo' => '000.08.06', 'name' => 'POUSADA'];
    	$ambientes[] = ['codigo' => '000.14.03', 'name' => 'PRACA'];
    	$ambientes[] = ['codigo' => '000.13.01', 'name' => 'PRESTACAO DE SERVICOS - CONSERTOS'];
    	$ambientes[] = ['codigo' => '000.13.06', 'name' => 'PRESTACAO DE SERVICOS - REPAROS'];
    	$ambientes[] = ['codigo' => '000.13.05', 'name' => 'PRESTACAO DE SERVICOS - VIGILANCIA / LIMPEZA'];
    	$ambientes[] = ['codigo' => '000.11.07', 'name' => 'QUARTEL POLICIA MILITAR'];
    	$ambientes[] = ['codigo' => '000.23.08', 'name' => 'REFUGIO DA VIDA SILVESTRE'];
    	$ambientes[] = ['codigo' => '000.12.05', 'name' => 'REPRESA'];
    	$ambientes[] = ['codigo' => '000.23.01', 'name' => 'RESERVA BIOLOGICA'];
    	$ambientes[] = ['codigo' => '000.23.12', 'name' => 'RESERVA DE DESENVOLVIMENTO SUSTENTAVEL'];
    	$ambientes[] = ['codigo' => '000.23.11', 'name' => 'RESERVA DE FAUNA'];
    	$ambientes[] = ['codigo' => '000.23.10', 'name' => 'RESERVA EXTRATIVISTA'];
    	$ambientes[] = ['codigo' => '000.12.07', 'name' => 'RESERVA LEGAL'];
    	$ambientes[] = ['codigo' => '000.23.14', 'name' => 'RESERVA PARTICULAR DE PATRIMONIO NATURAL (RPPN)'];
    	$ambientes[] = ['codigo' => '000.16.03', 'name' => 'RESIDENCIA'];
    	$ambientes[] = ['codigo' => '000.16.01', 'name' => 'RESIDENCIA ABANDONADA'];
    	$ambientes[] = ['codigo' => '000.16.05', 'name' => 'RESIDENCIA - PARTE EXTERNA'];
    	$ambientes[] = ['codigo' => '000.16.06', 'name' => 'RESIDENCIA SEM MORADOR'];
    	$ambientes[] = ['codigo' => '000.01.12', 'name' => 'RESTAURANTE'];
    	$ambientes[] = ['codigo' => '000.20.07', 'name' => 'RIO'];
    	$ambientes[] = ['codigo' => '000.07.13', 'name' => 'RODEIOS'];
    	$ambientes[] = ['codigo' => '000.14.06', 'name' => 'RODOVIA'];
    	$ambientes[] = ['codigo' => '000.14.10', 'name' => 'RODOVIA ESTADUAL'];
    	$ambientes[] = ['codigo' => '000.14.11', 'name' => 'RODOVIA FEDERAL'];
    	$ambientes[] = ['codigo' => '000.18.06', 'name' => 'RODOVIARIA'];
    	$ambientes[] = ['codigo' => '000.15.02', 'name' => 'SEMINARIO'];
    	$ambientes[] = ['codigo' => '000.04.18', 'name' => 'SHOPPING'];
    	$ambientes[] = ['codigo' => '000.07.14', 'name' => 'SHOW'];
    	$ambientes[] = ['codigo' => '000.02.11', 'name' => 'SINDICATO'];
    	$ambientes[] = ['codigo' => '000.20.03', 'name' => 'SITIO'];
    	$ambientes[] = ['codigo' => '000.01.13', 'name' => 'SORVETERIA'];
    	$ambientes[] = ['codigo' => '000.10.05', 'name' => 'SUPERMERCADO'];
    	$ambientes[] = ['codigo' => '000.18.07', 'name' => 'TAXI'];
    	$ambientes[] = ['codigo' => '000.01.14', 'name' => 'TEATRO'];
    	$ambientes[] = ['codigo' => '000.18.08', 'name' => 'TERMINAL'];
    	$ambientes[] = ['codigo' => '000.18.11', 'name' => 'TERMINAL FERROVIARIO'];
    	$ambientes[] = ['codigo' => '000.18.12', 'name' => 'TERMINAL RODOVIARIO'];
    	$ambientes[] = ['codigo' => '000.18.13', 'name' => 'TERMINAL URBANO'];
    	$ambientes[] = ['codigo' => '000.14.04', 'name' => 'TERRENO VAZIO'];
    	$ambientes[] = ['codigo' => '000.13.04', 'name' => 'TRANSPORTADORA'];
    	$ambientes[] = ['codigo' => '000.03.04', 'name' => 'TRANSPORTE DE VALORES'];
    	$ambientes[] = ['codigo' => '000.14.12', 'name' => 'TRILHA'];
    	$ambientes[] = ['codigo' => '000.18.09', 'name' => 'TUBO'];
    	$ambientes[] = ['codigo' => '000.18.14', 'name' => 'UBER'];
    	$ambientes[] = ['codigo' => '000.24.01', 'name' => 'UNIDADE DE ACOLHIMENTO'];
    	$ambientes[] = ['codigo' => '000.19.01', 'name' => 'VEICULO EM TRANSITO'];
    	$ambientes[] = ['codigo' => '000.19.02', 'name' => 'VEICULO ESTACIONADO'];
    	$ambientes[] = ['codigo' => '000.19.03', 'name' => 'VEICULO NO SEMAFORO'];
    	$ambientes[] = ['codigo' => '000.14.09', 'name' => 'VIA FLUVIAL'];
    	$ambientes[] = ['codigo' => '000.14.05', 'name' => 'VIA PUBLICA'];
    	$ambientes[] = ['codigo' => '000.14.07', 'name' => 'VIA PUBLICA ESTADUAL'];
    	$ambientes[] = ['codigo' => '000.14.08', 'name' => 'VIA PUBLICA FEDERAL'];
    	$ambientes[] = ['codigo' => '000.20.04', 'name' => 'VIA PUBLICA RURAL'];
    	$ambientes[] = ['codigo' => '000.11.09', 'name' => 'VIATURA'];
    	$ambientes[] = ['codigo' => '000.04.22', 'name' => 'VIDEO LOCADORA'];
    	
    	foreach ($ambientes as $key => $ambiente)
    	{
    		Ambiente::create($ambiente);
    	}
    }
}
